### ISSUE TITLE
Create ooziee package 4.0.0

### ISSUE THREAD

**Issue by javiroman** [keedio/buildoop#33]
Create package for OOZIE_VERSION=4.0.0_openbus-0.0.1-r1

**Comment by javiroman** [comment]
The package is created and is pending of test by users.

**Comment by danieltardon** [comment]
There's an error when it tries to start the daemon:

/usr/lib/oozie/bin/oozied.sh: line 104: /usr/lib/bigtop-tomcat/bin/catalina.sh: No such file or directory
/usr/lib/oozie/bin/oozied.sh: line 104: exec: /usr/lib/bigtop-tomcat/bin/catalina.sh: cannot execute: No such file or directory

It seems there are missing files.

In the oozie-env.sh file it exports a wrong path for CATALINA_HOME:
export OOZIE_CATALINA_HOME=/usr/lib/bigtop-tomcat

I've tried to workaround it by deploying an oozie-server (tomcat standalone server) directory from an oozie tarball installation in /usr/lib/oozie and changing the OOZIE_CATALINA_HOME variable to /usr/lib/oozie/oozie-server/. It seems to work for me as i can access the Oozie web console.

The next error i've found is while installing the share lib as Cloudera describes [1]:

$ sudo oozie-setup sharelib create -fs <FS_URI> -locallib /usr/lib/oozie/oozie-sharelib-yarn.tar.gz

If you try to install it as oozie user with "sudo -E -u oozie" it asks you for oozie's password. If you try to install the share lib as root the script fails with the next error:

Error: E0902: Exception occured: [Server IPC version 9 cannot communicate with client version 4]

Stack trace for the error was (for debug purposes):

org.apache.oozie.service.HadoopAccessorException: E0902: Exception occured: [Server IPC version 9 cannot communicate with client version 4]
    at org.apache.oozie.service.HadoopAccessorService.createFileSystem(HadoopAccessorService.java:430)
    at org.apache.oozie.tools.OozieSharelibCLI.run(OozieSharelibCLI.java:144)
    at org.apache.oozie.tools.OozieSharelibCLI.main(OozieSharelibCLI.java:52)
Caused by: org.apache.hadoop.ipc.RemoteException: Server IPC version 9 cannot communicate with client version 4
    at org.apache.hadoop.ipc.Client.call(Client.java:1107)
    at org.apache.hadoop.ipc.RPC$Invoker.invoke(RPC.java:229)
    at com.sun.proxy.$Proxy5.getProtocolVersion(Unknown Source)
    at org.apache.hadoop.ipc.RPC.getProxy(RPC.java:411)
    at org.apache.hadoop.hdfs.DFSClient.createRPCNamenode(DFSClient.java:135)
    at org.apache.hadoop.hdfs.DFSClient.<init>(DFSClient.java:276)
    at org.apache.hadoop.hdfs.DFSClient.<init>(DFSClient.java:241)
    at org.apache.hadoop.hdfs.DistributedFileSystem.initialize(DistributedFileSystem.java:100)
    at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:1411)
    at org.apache.hadoop.fs.FileSystem.access$200(FileSystem.java:66)
    at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:1429)
    at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:254)
    at org.apache.oozie.service.HadoopAccessorService$2.run(HadoopAccessorService.java:422)
    at org.apache.oozie.service.HadoopAccessorService$2.run(HadoopAccessorService.java:420)
    at java.security.AccessController.doPrivileged(Native Method)
    at javax.security.auth.Subject.doAs(Subject.java:415)
    at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1136)
    at org.apache.oozie.service.HadoopAccessorService.createFileSystem(HadoopAccessorService.java:420)
    ... 2 more

[1]http://www.cloudera.com/content/cloudera-content/cloudera-docs/CDH5/latest/CDH5-Installation-Guide/cdh5ig_topic_17_6.html?scroll=topic_17_6_4_unique_1

**Comment by javiroman** [comment]
The package bigtop-tomcat was included because of distributions like CentOS 5.x didn't shipped with recent versions of Tomcat [1]. Due to Buildoop support >= CentOS 6.x and those versions are shipping Tomcat 6, a more recent version of this Servlet Container and Webserver, this dependency of "in-house Tomcat package" was removed.

Because Oozie, and others need system-wide Tomcat server, those packages need depends on the standard distribution Tomcat package. The problem here is when we install the standard package "yum install tomcat6" this installation is plenty of dependencies of other packages, and one of them is the OpenJDK dependency, we need to avoid this dependency, because we are only supporting Oracle Sun JDKs. At this point we need to include a "in-house Tomcat package" as Bigtop project does it.

[1] https://issues.apache.org/jira/browse/BIGTOP-417

**Comment by danieltardon** [comment]
Ok. 

That was the reason why I tried to deploy a "bundled oozie-server" without installing tomcat and its dependencies.

I think the second error I've encountered is related to that bundle is not valid.

I'll try to test with different options and keep you updated in order to build the oozie package.

PS: The real Oozie version is 4.0.0 not 4.4.0 ;)

**Comment by javiroman** [comment]
Probably the server is woking fine right now:

$ sudo /etc/init.d/oozie start

Setting OOZIE_HOME:          /usr/lib/oozie
Sourcing:                    /usr/lib/oozie/bin/oozie-env.sh
  setting OOZIE_DATA=/var/lib/oozie
  setting OOZIE_CATALINA_HOME=/usr/lib/tomcatserver
  setting CATALINA_TMPDIR=/var/lib/oozie
  setting CATALINA_PID=/var/run/oozie/oozie.pid
  setting CATALINA_BASE=/var/lib/oozie/tomcat-deployment
  setting OOZIE_HTTPS_PORT=11443
  setting OOZIE_HTTPS_KEYSTORE_PASS=password
  setting CATALINA_OPTS="$CATALINA_OPTS -Doozie.https.port=${OOZIE_HTTPS_PORT}"
  setting CATALINA_OPTS="$CATALINA_OPTS -Doozie.https.keystore.pass=${OOZIE_HTTPS_KEYSTORE_PASS}"
  setting CATALINA_OPTS="$CATALINA_OPTS -Xmx1024m"
  setting OOZIE_CONFIG=/etc/oozie/conf
  setting OOZIE_LOG=/var/log/oozie
...
$ sudo jps
23156 DFSZKFailoverController
17743 JournalNode
18909 QuorumPeerMain
17837 NameNode
19175 Bootstrap
3514 JobHistoryServer
19379 Jps

**Comment by danieltardon** [comment]
The server seems to start fine but i get this error when i try to create the Oozie share lib in HDFS:

setting OOZIE_DATA=/var/lib/oozie
  setting OOZIE_CATALINA_HOME=/usr/lib/tomcatserver
  setting CATALINA_TMPDIR=/var/lib/oozie
  setting CATALINA_PID=/var/run/oozie/oozie.pid
  setting CATALINA_BASE=/var/lib/oozie/tomcat-deployment
  setting OOZIE_HTTPS_PORT=11443
  setting OOZIE_HTTPS_KEYSTORE_PASS=password
  setting CATALINA_OPTS="$CATALINA_OPTS -Doozie.https.port=${OOZIE_HTTPS_PORT}"
  setting CATALINA_OPTS="$CATALINA_OPTS -Doozie.https.keystore.pass=${OOZIE_HTTPS_KEYSTORE_PASS}"
  setting CATALINA_OPTS="$CATALINA_OPTS -Xmx1024m"
  setting OOZIE_CONFIG=/etc/oozie/conf
  setting OOZIE_LOG=/var/log/oozie
  setting OOZIE_DATA=/var/lib/oozie
  setting OOZIE_CATALINA_HOME=/usr/lib/tomcatserver
  setting CATALINA_TMPDIR=/var/lib/oozie
  setting CATALINA_PID=/var/run/oozie/oozie.pid
  setting CATALINA_BASE=/var/lib/oozie/tomcat-deployment
  setting OOZIE_HTTPS_PORT=11443
  setting OOZIE_HTTPS_KEYSTORE_PASS=password
  setting CATALINA_OPTS="$CATALINA_OPTS -Doozie.https.port=${OOZIE_HTTPS_PORT}"
  setting CATALINA_OPTS="$CATALINA_OPTS -Doozie.https.keystore.pass=${OOZIE_HTTPS_KEYSTORE_PASS}"
  setting CATALINA_OPTS="$CATALINA_OPTS -Xmx1024m"
  setting OOZIE_CONFIG=/etc/oozie/conf
  setting OOZIE_LOG=/var/log/oozie
log4j:WARN No appenders could be found for logger (org.apache.hadoop.util.Shell).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/hadoop/util/PlatformName
    at org.apache.hadoop.security.UserGroupInformation.getOSLoginModuleName(UserGroupInformation.java:303)
    at org.apache.hadoop.security.UserGroupInformation.<clinit>(UserGroupInformation.java:348)
    at org.apache.oozie.service.HadoopAccessorService.init(HadoopAccessorService.java:132)
    at org.apache.oozie.service.HadoopAccessorService.init(HadoopAccessorService.java:98)
    at org.apache.oozie.service.Services.setServiceInternal(Services.java:368)
    at org.apache.oozie.service.Services.setService(Services.java:354)
    at org.apache.oozie.service.Services.loadServices(Services.java:287)
    at org.apache.oozie.service.Services.init(Services.java:208)
    at org.apache.oozie.tools.OozieSharelibCLI.run(OozieSharelibCLI.java:136)
    at org.apache.oozie.tools.OozieSharelibCLI.main(OozieSharelibCLI.java:52)
Caused by: java.lang.ClassNotFoundException: org.apache.hadoop.util.PlatformName
    at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:425)

**Comment by javiroman** [comment]
The folder /usr/lib/oozie/lib has wrong *.jar files (version mismatch with the hadoop core installed)
The following files are wrong shipped in the package:

/usr/lib/oozie/lib/hadoop-auth-2.0.2-alpha.jar from "oozie-client-4.0.0-openbus0.0.1_1" package.
/usr/lib/oozie/libtools/hadoop-auth-2.0.2-alpha.jar from "oozie-4.0.0-openbus0.0.1_1" package.

This files must be symlinks to the core hadoop system:

rm /usr/lib/oozie/libtools/hadoop-auth-2.0.2-alpha.jar
rm /usr/lib/oozie/lib/hadoop-auth-2.0.2-alpha.jar
ln -s /usr/lib/hadoop/hadoop-auth.jar /usr/lib/oozie/lib/hadoop-auth.jar
ln -s /usr/lib/hadoop/hadoop-auth.jar /usr/lib/oozie/libtools/hadoop-auth.jar

This issue is related to: #42

**Comment by danieltardon** [comment]
Finally this fix the issue. 

I've managed to install the Oozie share libraries and everything seems to work fine. 

You can close the issue.

**Comment by javiroman** [comment]
Great!

**Comment by javiroman** [comment]
Fixed in commit 7e4a5ba3f9aa1201c0bdc90a39515045f13b6603
