### ISSUE TITLE
Random groovy.lang.GroovyRuntimeException: exception while reading process stream

### ISSUE THREAD

**Issue by javiroman** [keedio/buildoop#64]
Random exception in the RunCommand code:

[snip]
......
- exit 0
  Executing(%clean): /bin/sh -e /var/tmp/rpm-tmp.p8ACJw
  Exception in thread "Thread-1" groovy.lang.GroovyRuntimeException: exception while reading process stream
  at org.codehaus.groovy.runtime.ProcessGroovyMethods$TextDumper.run(ProcessGroovyMethods.java:488)
  at java.lang.Thread.run(Thread.java:744)
  Caused by: java.io.IOException: Stream closed
  at java.io.BufferedInputStream.getBufIfOpen(BufferedInputStream.java:162)
  at java.io.BufferedInputStream.read(BufferedInputStream.java:325)
  at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:283)
  at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:325)
  at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:177)
  at java.io.InputStreamReader.read(InputStreamReader.java:184)
  at java.io.BufferedReader.fill(BufferedReader.java:154)
  at java.io.BufferedReader.readLine(BufferedReader.java:317)
  at java.io.BufferedReader.readLine(BufferedReader.java:382)
  at org.codehaus.groovy.runtime.ProcessGroovyMethods$TextDumper.run(ProcessGroovyMethods.java:481)
  ... 1 more
  [INFO] ( bash -c rpmbuild -ba -D'_topdir .....

[snip]

This exception doesn't affect the final execution.

**Comment by javiroman** [comment]
Probably a solution in [1]

[1] http://jira.codehaus.org/browse/GROOVY-5406

**Comment by javiroman** [comment]
No fixed with the last commit, pending this post [1] about the problem.

[1] http://illegalargumentexception.blogspot.com.es/2008/10/java-how-not-to-make-mess-of-stream.html
